# Generated by Django 6.0.3 on 2026-04-08 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nepmart', '0002_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
