# Generated by Django 6.0.3 on 2026-04-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nepmart', '0003_rename_product_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
