# Generated by Django 6.0.3 on 2026-05-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepmart', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Card'), ('COD', 'Cash on Delivery')], max_length=10),
        ),
    ]
