# Generated by Django 6.0.1 on 2026-10-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepmart', '0009_category_product_brand_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('CARD', 'Card')], max_length=10),
        ),
    ]
